### ISSUE TITLE
high graphics detail level is not available on macOS, even though it should be

### ISSUE THREAD

**Issue by dmitshur** [XProger/OpenLara#356]
Very recently, I reported #354 about the macOS build having compilation errors. When I fixed the issue locally with a trivial fix of commenting out bad code (that used undeclared identifiers), I got used to high graphics detail levels being available:

![image](https://user-images.githubusercontent.com/1924134/123569083-ab5b8c00-d793-11eb-96fa-dd4d90c2b86c.png)

(The water looks incredible at "high".)

We went with a cleaner solution in PR #355, and after rebuilding at tip of master branch, I noticed the water was no longer the same. I investigated and found there was a pre-existing issue (which my simple local fix happened to take care of) and a problem I introduced in PR #355 itself, causing lower graphics settings to be available:

![image](https://user-images.githubusercontent.com/1924134/123569162-caf2b480-d793-11eb-9be6-a62e799e4e10.png)

I'll send a fix for this (which explains what happened in more detail).
