### PR TITLE
fix build, simplify imports on macOS 11 and 10.15

### LINKED ISSUE #354: src/platform/osx: build error on macOS Big Sur on Apple silicon due to undeclared OpenGL 3.0+ identifiers
When building from source on a MacBook Air with M1 (macOS Big Sur 11.4, Xcode 12.5.1), using the Xcode project in `src/platform/osx` directory, there are uses of the following undeclared identifiers in `src/gapi/gl.h` that cause build errors:

- `glGetStringi`
- `GL_NUM_EXTENSIONS`

Those identifiers are defined in OpenGL 3.0 and later, but `src/platform/osx` (on macOS) seems to target OpenGL 2.1 at this time.

<details><summary>Why OpenGL 2.1?</summary><br>

Specifically, in `src/gapi/gl.h`, under macOS case (when `__APPLE__` is defined but `_OS_IOS` is not):

```
#include <OpenGL/gl.h>
```

And in `src/platform/osx/main.mm`, a legacy OpenGL context is requested:

```
NSOpenGLPFAOpenGLProfile, NSOpenGLProfileVersionLegacy,
```

Which results in `GL_VERSION` having the value "2.1 Metal - 71.6.4".

<details><summary>What about OpenGL 4.1?</summary><br>

For reference, a 4.1 core profile can be successfully requested with:

```
NSOpenGLPFAOpenGLProfile, NSOpenGLProfileVersion4_1Core,
```

That results in `GL_VERSION` being "4.1 Metal - 71.6.4".

But shaders fail to compile because they don't have the `#version` directive which becomes mandatory.

</details>
</details>

### PR DESCRIPTION
**Pull request by dmitshur**
fix build on macOS 11 and 10.15, including on Apple silicon

There was a build error on macOS due to use of undeclared identifiers
glGetStringi and GL_NUM_EXTENSIONS. Those identifiers are declared in
OpenGL 3.0.

Switch from importing OpenGL/{gl.h,glext.h} to OpenGL/{gl3.h,gl3ext.h},
which fixes the problem. It also allows removing many OpenGL 3+ #defines,
though we do need to #define GL_LUMINANCE as was done in OpenGL/gl.h.
(It's also possible to keep the OpenGL/gl.h import, but it seems worse
to be importing both.)

Also remove #includes of Carbon/Carbon.h, OpenGL/OpenGL.h, AGL/agl.h,
since they don't seem to be needed.

Tested on macOS 11.4 (Big Sur) with Xcode 12.5.1 on Apple silicon,
and on macOS 10.15.7 (Catalina) with Xcode 12.4 on an Intel-based Mac.
(Hopefully this doesn't break older macOS platforms,
but unfortunately I can't test that easily.)

Fixes #354.

### CODE REVIEW

**Comment by dmitshur** [comment]
Thank you for the quick review and merge.
